name: Project3 CI CD

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:

  security:
    name: Security Scan
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # -------------------------
      # Bandit
      # -------------------------
      - name: Bandit Python Scan
        run: |
          python3 -m venv /tmp/project3-bandit
          /tmp/project3-bandit/bin/pip install bandit==1.9.4
          /tmp/project3-bandit/bin/bandit -r Skills_Utilization

      # -------------------------
      # Hadolint
      # -------------------------
      - name: Hadolint Dockerfile Scan
        run: |
          docker run --rm -i hadolint/hadolint:v2.15.1 \
          < Skills_Utilization/Dockerfile

      # -------------------------
      # TruffleHog
      # -------------------------
      - name: TruffleHog Secret Scan
        uses: trufflesecurity/trufflehog@v3.97.1
        with:
          path: ./
          extra_args: --only-verified


  build:
    name: Build
    needs: security
    runs-on: self-hosted

    steps:
      - name: Update Project3
        run: |
          cd /home/aau/Desktop/project3
          git pull origin main

      - name: Build Docker Image
        run: |
          cd /home/aau/Desktop/project3
          docker compose build


  deploy:
    name: Deploy
    needs: build
    runs-on: self-hosted

    steps:
      - name: Deploy with Vault
        run: |
          cd /home/aau/Desktop/project3
          ./vault.sh

      - name: Check Containers
        run: |
          cd /home/aau/Desktop/project3
          docker compose ps
