name: Deploy Project3

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Update Project3
        run: |
          cd /home/aau/Desktop/project3
          git pull origin main

      - name: Deploy with Vault
        run: |
          cd /home/aau/Desktop/project3
          ./vault.sh

      - name: Check containers
        run: |
          cd /home/aau/Desktop/project3
          docker compose ps
