name: Build and Deploy Project3

on:
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: self-hosted

    steps:
      - name: Update Project3
        run: |
          cd /home/aau/Desktop/project3
          git pull origin main

      - name: Build Docker Image
        run: |
          cd /home/aau/Desktop/project3
          docker compose build


  deploy:
    name: Deploy
    needs: build
    runs-on: self-hosted

    steps:
      - name: Deploy with Vault
        run: |
          cd /home/aau/Desktop/project3
          ./vault.sh

      - name: Check Containers
        run: |
          cd /home/aau/Desktop/project3
          docker compose ps
